server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

weChat:
  appId: wxd3ea51a6de85fb58
  secret: 99c43c71177d53b004b13d0ae2578991

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      connectionInitSql: set names utf8mb4 COLLATE utf8mb4_unicode_ci
      # connectionTestQuery: select 1

  # 缓存
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

  # Spring Data JPA
  jpa:
    show-sql: false
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

# 日志
logging:
  file: logs/demo.log
  level:
    root: warn